<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="Midhuns-Air.bbrouter" failures="1" tests="7" name="com.swaglabs.testcases.TestLoginFunctionality" time="18.056" errors="0" timestamp="2024-02-03T15:04:01 IST" skipped="1">
  <testcase classname="com.swaglabs.testcases.TestLoginFunctionality" name="testWithBlankFields" time="2.189"/>
  <testcase classname="com.swaglabs.testcases.TestLoginFunctionality" name="testWithInvalidUsername" time="2.120"/>
  <testcase classname="com.swaglabs.testcases.TestLoginFunctionality" name="testWithInvalidPassword" time="2.184">
    <skipped/>
  </testcase> <!-- testWithInvalidPassword -->
  <testcase classname="com.swaglabs.testcases.TestLoginFunctionality" name="testWithLockedUser" time="2.113"/>
  <testcase classname="com.swaglabs.testcases.TestLoginFunctionality" name="testWithValidCredentials" time="4.043"/>
  <testcase classname="com.swaglabs.testcases.TestLoginFunctionality" name="testLogout" time="2.942"/>
  <testcase classname="com.swaglabs.testcases.TestLoginFunctionality" name="testWithInvalidPassword" time="2.465">
    <failure message="" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: 
at org.testng.AssertJUnit.fail(AssertJUnit.java:65)
at org.testng.AssertJUnit.assertTrue(AssertJUnit.java:23)
at org.testng.AssertJUnit.assertTrue(AssertJUnit.java:33)
at com.swaglabs.testcases.TestLoginFunctionality.testWithInvalidPassword(TestLoginFunctionality.java:39)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:664)
at org.testng.internal.invokers.TestInvoker.retryFailed(TestInvoker.java:249)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:76)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:961)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:201)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:148)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:819)
at org.testng.TestRunner.run(TestRunner.java:619)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:443)
at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:481)
at org.testng.internal.thread.ThreadUtil.lambda$execute$0(ThreadUtil.java:58)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
at java.base/java.lang.Thread.run(Thread.java:833)
]]>
    </failure>
  </testcase> <!-- testWithInvalidPassword -->
</testsuite> <!-- com.swaglabs.testcases.TestLoginFunctionality -->
